[package]
name = "wasmparser-dump"
version = "0.1.1"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasm-tools"
description = "Utility to dump debug information about the wasm binary format"

[dependencies]
anyhow = "1"
wasmparser = { path = "../wasmparser", package = "wasmparser-nostd", version = "0.83.0", default-features = false }

[features]
default = ["std"]
std = ["wasmparser/std"]
